version: '2'
services:
  # Web Server
  nginx:
    build: ./nginx
    container_name: lnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    #source code container
    volumes_from:
      - www
    volumes:
      - ./nginx/logs:/var/log/nginx
    links:
      - php-fpm
  # PHP-FPM
  php-fpm:
    build: ./php-fpm
    container_name: lnmp-php-fpm
    ports:
      - "9000:9000"
      #source code container
    volumes_from:
      - www
    volumes:
      #php.ini
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    links:
      - mariadb
      - redis
  php-supervisor:
    build: ./php-supervisor
    container_name: lnmp-php-supervisor
    volumes:
      - ./php-supervisor/supervisor/log:/var/log/supervisor
    volumes_from:
       - www
    links:
      - mariadb
      - redis
  call-websocket:
    build: ./call-websocket
    container_name: lnmp-call-websocket
    volumes_from:
      - www
    ports:
      - "8190:8190"
      - "8191:8191"
    restart: always
  # MariaDB - One of the most popular database servers. Made by the original developers of MySQL. Guaranteed to stay open source.
  mariadb:
    image: mariadb
    container_name: lnmp-mariadb
    ports:
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mariadb/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
      - MYSQL_ROOT_PASSWORD=developer
  # Redis
  redis:
    image: redis
    container_name: lnmp-redis
    ports:
      - "6379:6379"
  # Web application code container
  www:
    image: tianon/true
    container_name: lnmp-www
    volumes:
      - ./www:/usr/share/nginx/html
