version: '2'
services:
  # Web Server
  nginx:
    build: ./nginx
    container_name: lnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    #source code container
    volumes_from:
      - www
    volumes:
      - "./nginx/logs:/var/log/nginx"
    links:
      - php-fpm:php-fpm
  # PHP-FPM
  php-fpm:
    image: bravist/php-fpm-alpine-aliyun-app:1.5
    container_name: lnmp-php-fpm
    ports:
      - "9000:9000"
      #source code container
    volumes_from:
      - www
    #https://github.com/laradock/laradock/issues/435
    extra_hosts:
      - "${PHP_FPM_DOMAIN}:${DOCKER_HOST_IP}"
      - "${PHP_FPM_DOMAIN2}:${DOCKER_HOST_IP}"
      - "${PHP_FPM_DOMAIN3}:${DOCKER_HOST_IP}"
      - "${PHP_FPM_DOMAIN4}:${DOCKER_HOST_IP}"
      - "${PHP_FPM_DOMAIN5}:${DOCKER_HOST_IP}"
    env_file: 
      - .env
  php-supervisor:
    build: ./php-supervisor
    container_name: lnmp-php-supervisor
    volumes:
      - ./php-supervisor/supervisor/log:/var/log/supervisor
    volumes_from:
       - www
    extra_hosts:
      - "${SUPERVISOR_DOMAIN}:${DOCKER_HOST_IP}"
      - "${SUPERVISOR_DOMAIN2}:${DOCKER_HOST_IP}"
      - "${SUPERVISOR_DOMAIN3}:${DOCKER_HOST_IP}"
      - "${SUPERVISOR_DOMAIN4}:${DOCKER_HOST_IP}"
      - "${SUPERVISOR_DOMAIN5}:${DOCKER_HOST_IP}"
    env_file: 
      - .env
  call-websocket:
    build: ./call-websocket
    container_name: lnmp-call-websocket
    volumes_from:
      - www
    ports:
      - "8190:8190"
      - "8191:8191"
    restart: always
  php-crond:
    build: ./php-crond
    container_name: lnmp-php-crond
    volumes_from:
      - "www"
    volumes:
      - "./php-crond/crontabs:/var/log/cron"
  # Web application code container
  www:
    image: tianon/true
    container_name: lnmp-www
    volumes:
      - ./www:/usr/share/nginx/html
