version: '2'
services:
  # Web Server
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    #source code container
    volumes_from:
      - www
    volumes:
      #nginx config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # certificates
      #- ./nginx/cert/:/etc/nginx/cert:ro
    links:
      - php-fpm
  # PHP-FPM
  php-fpm:
    build: ./php-fpm
    ports:
      - "9000:9000"
      #source code container
    volumes_from:
      - www
    volumes:
      #php.ini
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    links:
      - mariadb
      - redis
      - composer
  # PHP-FPM
  php-cli:
    build: ./php-cli
    ports:
      - "8190:8190"
     #source code container
    volumes_from:
      - www
    volumes:
      #php.ini
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    links:
      - mariadb
      - redis
      - composer
  # MariaDB
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mariadb/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
      - MYSQL_ROOT_PASSWORD=developer
  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  # Composer
  composer:
    image: lucor/composer
  # 运行composer: docker-compose run composer install
  # https://github.com/RobLoach/docker-composer/issues/88#issuecomment-229213544

  #docker run --rm -ti -v $(pwd):/app lucor/composer for composer 1.4.1
  #source code container
  www:
    image: tianon/true
    volumes:
      - ./www:/usr/share/nginx/html
