version: '2.1'
services:
  ### Nginx Web Container #######################################
  nginx:
    build: ./nginx
    container_name: lnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    #source code container
    volumes_from:
      - www
    volumes:
      - "./nginx/logs:/var/log/nginx"
    links:
      - php-fpm:php-fpm
    networks:
      web_server_network:
        ipv4_address: ${NGINX_WEB_SERVER_IP}

  ### PHP-FPM Container #######################################
  php-fpm:
    image: bravist/php-fpm-alpine-aliyun-app:1.13
    container_name: lnmp-php-fpm
    ports:
      - "9000:9000"
      #source code container
    volumes_from:
      - www
    #https://github.com/laradock/laradock/issues/435
    extra_hosts:
      - "${PHP_FPM_DOMAIN}:${NGINX_WEB_SERVER_IP}"
      - "${PHP_FPM_DOMAIN2}:${NGINX_WEB_SERVER_IP}"
      - "${PHP_FPM_DOMAIN3}:${NGINX_WEB_SERVER_IP}"
      - "${PHP_FPM_DOMAIN4}:${NGINX_WEB_SERVER_IP}"
      - "${PHP_FPM_DOMAIN5}:${NGINX_WEB_SERVER_IP}"
    env_file:
      - .env
    networks:
      - web_server_network

  ### Web-Root Container #######################################
  www:
    image: tianon/true
    container_name: lnmp-www
    volumes:
      - ./www:/usr/share/nginx/html

### Networks Setup ############################################
networks:
  web_server_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "${WEB_SERVER_SUBNET}"
        gateway: "${WEB_SERVER_GATEWAY}"
